export const CHARACTERS_ACTION_TYPES = {
	SET_CHARACTERS: "SET_CHARACTERS",
	RESET_CHARACTERS: "RESET_CHARACTERS",
	SET_CHARACTER_COUNT: "SET_CHARACTER_COUNT",
	SET_CURRENT_CHARACTERS: "SET_CURRENT_CHARACTERS",
	SET_CHARACTER: "SET_CHARACTER",
};
